SET LINESIZE 1000;
SET WRAP OFF
ALTER SESSION SET NLS_COMP=LINGUISTIC; -- comparasing without register
ALTER SESSION SET NLS_SORT=BINARY_CI;
ALTER SESSION SET NLS_LANG=RUSSIAN.RUSSIA.UTF8;
ALTER SESSION SET NLS_TERRITORY=RUSSIA;

